
package com.aisinogd.fp.dzfp.companyinterface.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.aisinogd.fp.dzfp.companyinterface.hessian.pojo.ElectroniceBatchQuery;
import com.aisinogd.fp.dzfp.companyinterface.hessian.pojo.ElectroniceInfo;
import com.aisinogd.fp.dzfp.companyinterface.hessian.pojo.ElectroniceStock;
import com.aisinogd.fp.dzfp.companyinterface.hessian.pojo.ReturnBuyerList;
import com.aisinogd.fp.dzfp.companyinterface.hessian.pojo.ReturnElectronice;
import com.aisinogd.fp.dzfp.companyinterface.hessian.pojo.ReturnElectroniceBatchList;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IEliWebServicePortType", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
@XmlSeeAlso({
    com.aisinogd.fp.dzfp.companyinterface.hessian.pojo.ObjectFactory.class,
    com.aisinogd.fp.dzfp.companyinterface.webservice.ObjectFactory.class
})
public interface IEliWebServicePortType {


    /**
     * 
     * @param in0
     * @return
     *     returns com.aisinogd.fp.dzfp.companyinterface.hessian.pojo.ReturnElectronice
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
    @RequestWrapper(localName = "invEli", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.InvEli")
    @ResponseWrapper(localName = "invEliResponse", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.InvEliResponse")
    public ReturnElectronice invEli(
        @WebParam(name = "in0", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
        ElectroniceInfo in0);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
    @RequestWrapper(localName = "queryDiskInfo", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.QueryDiskInfo")
    @ResponseWrapper(localName = "queryDiskInfoResponse", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.QueryDiskInfoResponse")
    public String queryDiskInfo(
        @WebParam(name = "in0", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
        String in2);

    /**
     * 
     * @param in0
     * @return
     *     returns com.aisinogd.fp.dzfp.companyinterface.hessian.pojo.ElectroniceInfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
    @RequestWrapper(localName = "queryEleDetails", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.QueryEleDetails")
    @ResponseWrapper(localName = "queryEleDetailsResponse", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.QueryEleDetailsResponse")
    public ElectroniceInfo queryEleDetails(
        @WebParam(name = "in0", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
        ElectroniceInfo in0);

    /**
     * 
     * @param in0
     * @return
     *     returns com.aisinogd.fp.dzfp.companyinterface.hessian.pojo.ReturnElectronice
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
    @RequestWrapper(localName = "pdfToPng", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.PdfToPng")
    @ResponseWrapper(localName = "pdfToPngResponse", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.PdfToPngResponse")
    public ReturnElectronice pdfToPng(
        @WebParam(name = "in0", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
        ElectroniceInfo in0);

    /**
     * 
     * @param in0
     * @return
     *     returns com.aisinogd.fp.dzfp.companyinterface.hessian.pojo.ElectroniceStock
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
    @RequestWrapper(localName = "queryEliStock", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.QueryEliStock")
    @ResponseWrapper(localName = "queryEliStockResponse", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.QueryEliStockResponse")
    public ElectroniceStock queryEliStock(
        @WebParam(name = "in0", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns com.aisinogd.fp.dzfp.companyinterface.hessian.pojo.ReturnElectronice
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
    @RequestWrapper(localName = "sendToInvEli", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.SendToInvEli")
    @ResponseWrapper(localName = "sendToInvEliResponse", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.SendToInvEliResponse")
    public ReturnElectronice sendToInvEli(
        @WebParam(name = "in0", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
        ElectroniceInfo in0);

    /**
     * 
     * @param in0
     * @return
     *     returns com.aisinogd.fp.dzfp.companyinterface.hessian.pojo.ReturnElectronice
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
    @RequestWrapper(localName = "wechatInvByProG", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.WechatInvByProG")
    @ResponseWrapper(localName = "wechatInvByProGResponse", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.WechatInvByProGResponse")
    public ReturnElectronice wechatInvByProG(
        @WebParam(name = "in0", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
        ElectroniceInfo in0);

    /**
     * 
     * @param in0
     * @return
     *     returns com.aisinogd.fp.dzfp.companyinterface.hessian.pojo.ReturnBuyerList
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
    @RequestWrapper(localName = "buyerNameListByName", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.BuyerNameListByName")
    @ResponseWrapper(localName = "buyerNameListByNameResponse", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.BuyerNameListByNameResponse")
    public ReturnBuyerList buyerNameListByName(
        @WebParam(name = "in0", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns com.aisinogd.fp.dzfp.companyinterface.hessian.pojo.ReturnElectroniceBatchList
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
    @RequestWrapper(localName = "queryEliDataByBZ", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.QueryEliDataByBZ")
    @ResponseWrapper(localName = "queryEliDataByBZResponse", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.QueryEliDataByBZResponse")
    public ReturnElectroniceBatchList queryEliDataByBZ(
        @WebParam(name = "in0", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns com.aisinogd.fp.dzfp.companyinterface.hessian.pojo.ReturnElectronice
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
    @RequestWrapper(localName = "queryEliData", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.QueryEliData")
    @ResponseWrapper(localName = "queryEliDataResponse", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.QueryEliDataResponse")
    public ReturnElectronice queryEliData(
        @WebParam(name = "in0", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
        ElectroniceInfo in0);

    /**
     * 
     * @param in0
     * @return
     *     returns com.aisinogd.fp.dzfp.companyinterface.hessian.pojo.ReturnElectronice
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
    @RequestWrapper(localName = "wechatInv", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.WechatInv")
    @ResponseWrapper(localName = "wechatInvResponse", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.WechatInvResponse")
    public ReturnElectronice wechatInv(
        @WebParam(name = "in0", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
        ElectroniceInfo in0);

    /**
     * 
     * @param in0
     * @return
     *     returns com.aisinogd.fp.dzfp.companyinterface.hessian.pojo.ReturnElectronice
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
    @RequestWrapper(localName = "autoSendByEmail", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.AutoSendByEmail")
    @ResponseWrapper(localName = "autoSendByEmailResponse", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.AutoSendByEmailResponse")
    public ReturnElectronice autoSendByEmail(
        @WebParam(name = "in0", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
        ElectroniceInfo in0);

    /**
     * 
     * @param in0
     * @return
     *     returns com.aisinogd.fp.dzfp.companyinterface.hessian.pojo.ReturnElectroniceBatchList
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
    @RequestWrapper(localName = "queryEliBatchData", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.QueryEliBatchData")
    @ResponseWrapper(localName = "queryEliBatchDataResponse", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", className = "com.aisinogd.fp.dzfp.companyinterface.webservice.QueryEliBatchDataResponse")
    public ReturnElectroniceBatchList queryEliBatchData(
        @WebParam(name = "in0", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com")
        ElectroniceBatchQuery in0);

}
