
package com.aisinogd.fp.dzfp.companyinterface.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "IEliWebService", targetNamespace = "http://webservice.companyInterface.dzfp.fp.aisinogd.com", wsdlLocation = "http://14.18.206.50/eligzjj/eliWebService.ws?wsdl")
public class IEliWebService
        extends Service {

    private final static URL IELIWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException IELIWEBSERVICE_EXCEPTION;
    private final static QName IELIWEBSERVICE_QNAME = new QName("http://webservice.companyInterface.dzfp.fp.aisinogd.com", "IEliWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://14.18.206.50/eligzjj/eliWebService.ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IELIWEBSERVICE_WSDL_LOCATION = url;
        IELIWEBSERVICE_EXCEPTION = e;
    }

    public IEliWebService() {
        super(__getWsdlLocation(), IELIWEBSERVICE_QNAME);
    }

    public IEliWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IELIWEBSERVICE_QNAME, features);
    }

    public IEliWebService(URL wsdlLocation) {
        super(wsdlLocation, IELIWEBSERVICE_QNAME);
    }

    public IEliWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IELIWEBSERVICE_QNAME, features);
    }

    public IEliWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IEliWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns IEliWebServicePortType
     */
    @WebEndpoint(name = "IEliWebServiceHttpPort")
    public IEliWebServicePortType getIEliWebServiceHttpPort() {
        return super.getPort(new QName("http://webservice.companyInterface.dzfp.fp.aisinogd.com", "IEliWebServiceHttpPort"), IEliWebServicePortType.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns IEliWebServicePortType
     */
    @WebEndpoint(name = "IEliWebServiceHttpPort")
    public IEliWebServicePortType getIEliWebServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.companyInterface.dzfp.fp.aisinogd.com", "IEliWebServiceHttpPort"), IEliWebServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IELIWEBSERVICE_EXCEPTION != null) {
            throw IELIWEBSERVICE_EXCEPTION;
        }
        return IELIWEBSERVICE_WSDL_LOCATION;
    }

}
